### ISSUE TITLE
Problems in Google App Engine

### ISSUE THREAD

**Issue by micheleorsi** [pengrad/java-telegram-bot-api#9]
Hi, 
I tried to use this lib on Google App Engine, but I continue to get this problem with several classes:

<pre>Unable to invoke no-args constructor for class com.pengrad.telegrambot.model.Update. Register an InstanceCreator with Gson for this type may fix this problem.</p><h3>Caused by:</h3>java.lang.RuntimeException: Unable to invoke no-args constructor for class com.pengrad.telegrambot.model.Update. Register an InstanceCreator with Gson for this type may fix this problem.</pre>

I tried to register an InstanceCreator but I continue to get this problem, so I added some empty constructors in the model classes. But then I had to remove "final" from class attributes.
Have you got any other suggestion to fix it? Otherwise I am going to send you a pull request.

Thanks

**Comment by pengrad** [comment]
Hi,
Why do you need to explicitly create model instances?
You can get updates by `bot.getUpdates` or if you are using webhook by `BotUtils.parseUpdate()`

**Comment by micheleorsi** [comment]
Well, that is  the problem: I used the command for webhook, but when it runs I get the error I mentioned..
Google App Engine is an environment that limits the full power of JDK, expecially reflection.. Could it be the problem?

**Comment by pengrad** [comment]
Don't really understand what you mean "i used the command for webhook".
Did you call `gson.fromJson()` by yourself?
Please provide the code how you create model classes.

**Comment by pengrad** [comment]
Ok, you are right. 
Class sun.misc.Unsafe is restricted on Google AppEngine. And it's used by Gson with classes without no-args constructor. 
Will try to do something. 
Thanks!

**Comment by micheleorsi** [comment]
Ok, thanks
In any case if you have something in kind and you don't have tine to fix, just let me know and I can implement. I am happy to help!

**Comment by pengrad** [comment]
Fixed in 1.3.0
Thanks!

**Comment by micheleorsi** [comment]
Just tested and it works perfect!
One thing: now I see the constructors for Update, Message and Chat are not anymore public. Would it be possible to have a static builder for them? Or something to construct an instance of such instances without using the parser? I need  that in order to test the code I am writing!

Thanks

**Comment by micheleorsi** [comment]
Sorry I tested on my laptop and it worked, but now I deployed to Google App Engine and I have a new error:

<pre>retrofit.RetrofitError: java.lang.IllegalAccessException: Reflection is not allowed on private final int java.lang.ThreadLocal.threadLocalHashCode
	at retrofit.RetrofitError.unexpectedError(RetrofitError.java:44)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy19.sendMessage(Unknown Source)
	at com.pengrad.telegrambot.TelegramBot.sendMessage(TelegramBot.java:47)</pre>

I tried to make the model constructors public but I still got this error

**Comment by micheleorsi** [comment]
(yes, I already tried to make all the constructors public, but the error is still there)

**Comment by pengrad** [comment]
Did it work before? I didn't change anything in `sendMessage`. 
Seems like error could be inside Retrofit.

**Comment by micheleorsi** [comment]
Well at the moment I found a solution quick and dirty:
* new branch from the version 1.2.4 called 'gae' 
* removed 'final' in private properties of the model
* added public empty constructor

The strange thing is that you didn't change retrofit version, I will have a look better in the next days. 
For the moment I had to go quick, since I have a demo today to some friends!

**Comment by pengrad** [comment]
Really strange. 
Come back soon, we'll try to fix this in version 1.3 :)

**Comment by pengrad** [comment]
Seems fixed in 2.0.0
